# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: grg

before:
  hooks:
    - go mod tidy

builds:
  - id: grg
    main: ./cmd/grg
    binary: grg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: "386"
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: "386"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/kryft-dev/grg/internal/cli.AppVersion={{.Version}}
      - -X github.com/kryft-dev/grg/internal/cli.GitCommit={{.Commit}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    formats:
      - binary

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"
